cache:
  - file: Gemfile.lock
    path: .bundle
services:
  rails:
    port: 3000
    image: reploy/ruby:2.6.3
    environment:
      GEM_HOME: "/local/.bundle"
      BUNDLE_PATH: "/local/.bundle"
    build:
      - bundle install
    serve:
      # - yarn --verify-tree
      - rake db:migrate
      - bundle exec rails s -b 0.0.0.0
  sidekiq:
    do-not-expose: true
    port: 3001
    image: reploy/ruby:2.6.3
    environment:
      GEM_HOME: "/local/.bundle"
      BUNDLE_PATH: "/local/.bundle"
    build:
      - bundle install
    serve:
      # - yarn --verify-tree
      - rake db:migrate
      - bundle exec sidekiq  
  postgres:
    port: 5432
    runtime: postgres
    do-not-expose: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    do-not-expose: true
    port: 6379
    runtime: redis
